serial:
  port: "/dev/ttyUSB0"
  baudrate: 115200

yolo:
  xml_path: "../models/armor_yolov11s.xml"
  bin_path: "../models/armor_yolov11s.bin"

camera:
  matrix_path: "../config/camera_matrix.yaml"
  exposure_time: 1000
  gain: 16.0

number_classifier:
    model_path: "../models/mlp.onnx"
    label_path: "../models/label.txt"